#!/bin/sh

workspaces() {
    ws1=1
    ws2=2
    ws3=3
    ws4=4
    ws5=5
    ws6=6

    # Unoccupied
    un="_0"

    # Check if Occupied
    o1=$(hyprctl workspaces | grep -A 5 "ID $ws1 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')
    o2=$(hyprctl workspaces | grep -A 5 "ID $ws2 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')
    o3=$(hyprctl workspaces | grep -A 5 "ID $ws3 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')
    o4=$(hyprctl workspaces | grep -A 5 "ID $ws4 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')
    o5=$(hyprctl workspaces | grep -A 5 "ID $ws5 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')
    o6=$(hyprctl workspaces | grep -A 5 "ID $ws6 " | head -n 1 | wc -l | awk '{if ($1 != 0) print $1}')

    # Check if Focused
    f1=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws1" | wc -l | awk '{if ($1 != 0) print $1}')
    f2=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws2" | wc -l | awk '{if ($1 != 0) print $1}')
    f3=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws3" | wc -l | awk '{if ($1 != 0) print $1}')
    f4=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws4" | wc -l | awk '{if ($1 != 0) print $1}')
    f5=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws5" | wc -l | awk '{if ($1 != 0) print $1}')
    f6=$(hyprctl activeworkspace | head -n 1 | grep "workspace ID $ws6" | wc -l | awk '{if ($1 != 0) print $1}')

    echo "(box :class \"works\" :orientation \"v\" :halign \"center\" :valign \"start\" :space-evenly \"false\" :spacing \"-5\" \
    (button :onclick \"hyprctl dispatch workspace $ws1\" :class \"$un$o1$f1\" \"\") \
    (button :onclick \"hyprctl dispatch workspace $ws2\" :class \"$un$o2$f2\" \"\") \
    (button :onclick \"hyprctl dispatch workspace $ws3\" :class \"$un$o3$f3\" \"\") \
    (button :onclick \"hyprctl dispatch workspace $ws4\" :class \"$un$o4$f4\" \"\") \
    (button :onclick \"hyprctl dispatch workspace $ws5\" :class \"$un$o5$f5\" \"\") \
    (button :onclick \"hyprctl dispatch workspace $ws6\" :class \"$un$o6$f6\" \"\"))"
}

workspaces

socat -u UNIX-CONNECT:/run/user/"$UID"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r _; do
    workspaces
done

