local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = "Find Project Files" })
vim.keymap.set('n', '<leader>pg', builtin.git_files, { desc = "Find Git Fiels" })
vim.keymap.set("n", "<leader>ps", function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Grep files" })
